# Generated by Django 3.2.15 on 2024-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatmessage_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
