# Generated by Django 3.2.15 on 2024-03-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_chatsession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='users.chatsession'),
        ),
    ]
