# Generated by Django 3.2.15 on 2024-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_chatmessage_chat_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_subject',
            field=models.TextField(blank=True, default='No Subject', null=True),
        ),
    ]
