# Generated by Django 3.2.15 on 2024-04-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_chatmessage_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
